// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dblayer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Childcomment struct {
	Parentcommentid int32
	Childcommentid  int32
	Userid          int32
	Pageid          int32
	Createdat       pgtype.Timestamp
	Content         string
}

type Likeshistory struct {
	Pageid    int32
	Userid    int32
	Commentid int32
	Likevalue int32
}

type Page struct {
	Pageurl       string
	Pageid        int32
	Commentscount int32
	Createdat     pgtype.Timestamp
	Pagesummary   string
	Pagescore     int32
}

type Parentcomment struct {
	Commentid         int32
	Pageid            int32
	Userid            int32
	Createdat         pgtype.Timestamp
	Upvotes           int32
	Downvotes         int32
	Content           string
	Sentimentscore    int32
	Childcommentcount int32
}

type User struct {
	Userid       int32
	Username     string
	Fullname     string
	Emailid      string
	Joineddate   pgtype.Timestamp
	Aboutme      string
	Passwordhash string
}
