// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dblayer

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg *CreateCommentParams) error
	CreatePage(ctx context.Context, pageurl string) error
	CreateUser(ctx context.Context, arg *CreateUserParams) error
	IncreaseCommentCount(ctx context.Context, pageid int32) error
	RetrieveNewstComments(ctx context.Context, arg *RetrieveNewstCommentsParams) ([]*RetrieveNewstCommentsRow, error)
	RetrieveOldestComments(ctx context.Context, arg *RetrieveOldestCommentsParams) ([]*RetrieveOldestCommentsRow, error)
	RetrievePageDetails(ctx context.Context, pageurl string) (*RetrievePageDetailsRow, error)
	RetrieveSubComments(ctx context.Context, arg *RetrieveSubCommentsParams) ([]*RetrieveSubCommentsRow, error)
	UpdateComment(ctx context.Context, arg *UpdateCommentParams) error
	UpdateEmailId(ctx context.Context, arg *UpdateEmailIdParams) error
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
