insert into comments (PageId, UserId, CommentData) values (5, 43, 'Distributed object-oriented middleware');
insert into comments (PageId, UserId, CommentData) values (5, 34, 'Pre-emptive explicit instruction set');
insert into comments (PageId, UserId, CommentData) values (1, 44, 'Exclusive tertiary website');
insert into comments (PageId, UserId, CommentData) values (8, 49, 'Versatile bottom-line productivity');
insert into comments (PageId, UserId, CommentData) values (4, 37, 'Devolved discrete installation');
insert into comments (PageId, UserId, CommentData) values (3, 27, 'Re-engineered 3rd generation benchmark');
insert into comments (PageId, UserId, CommentData) values (2, 10, 'Intuitive secondary instruction set');
insert into comments (PageId, UserId, CommentData) values (5, 12, 'Vision-oriented upward-trending info-mediaries');
insert into comments (PageId, UserId, CommentData) values (1, 23, 'Profit-focused background moratorium');
insert into comments (PageId, UserId, CommentData) values (9, 18, 'Right-sized static intranet');
insert into comments (PageId, UserId, CommentData) values (10, 50, 'Multi-lateral logistical moratorium');
insert into comments (PageId, UserId, CommentData) values (3, 32, 'Seamless zero administration structure');
insert into comments (PageId, UserId, CommentData) values (6, 44, 'Down-sized zero defect data-warehouse');
insert into comments (PageId, UserId, CommentData) values (5, 45, 'Face to face upward-trending challenge');
insert into comments (PageId, UserId, CommentData) values (3, 36, 'Advanced bottom-line standardization');
insert into comments (PageId, UserId, CommentData) values (7, 43, 'Secured logistical initiative');
insert into comments (PageId, UserId, CommentData) values (6, 32, 'Robust global task-force');
insert into comments (PageId, UserId, CommentData) values (10, 48, 'Diverse bottom-line throughput');
insert into comments (PageId, UserId, CommentData) values (3, 12, 'Optimized attitude-oriented budgetary management');
insert into comments (PageId, UserId, CommentData) values (6, 47, 'Devolved eco-centric support');
insert into comments (PageId, UserId, CommentData) values (7, 36, 'Focused tertiary encryption');
insert into comments (PageId, UserId, CommentData) values (10, 21, 'Reduced client-driven throughput');
insert into comments (PageId, UserId, CommentData) values (8, 6, 'User-friendly multi-tasking archive');
insert into comments (PageId, UserId, CommentData) values (7, 37, 'Enhanced tangible implementation');
insert into comments (PageId, UserId, CommentData) values (4, 31, 'Implemented zero administration analyzer');
insert into comments (PageId, UserId, CommentData) values (6, 20, 'Multi-lateral optimal attitude');
insert into comments (PageId, UserId, CommentData) values (4, 10, 'Profound next generation conglomeration');
insert into comments (PageId, UserId, CommentData) values (3, 4, 'Managed 4th generation data-warehouse');
insert into comments (PageId, UserId, CommentData) values (2, 12, 'Synergistic real-time secured line');
insert into comments (PageId, UserId, CommentData) values (10, 5, 'Visionary encompassing parallelism');
insert into comments (PageId, UserId, CommentData) values (7, 13, 'Adaptive contextually-based focus group');
insert into comments (PageId, UserId, CommentData) values (3, 3, 'Cross-platform coherent open system');
insert into comments (PageId, UserId, CommentData) values (8, 25, 'Up-sized methodical workforce');
insert into comments (PageId, UserId, CommentData) values (10, 30, 'Vision-oriented composite array');
insert into comments (PageId, UserId, CommentData) values (9, 35, 'Optional systemic ability');
insert into comments (PageId, UserId, CommentData) values (3, 25, 'Self-enabling incremental complexity');
insert into comments (PageId, UserId, CommentData) values (4, 39, 'Total leading edge policy');
insert into comments (PageId, UserId, CommentData) values (2, 35, 'Multi-layered explicit artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (5, 30, 'Automated maximized migration');
insert into comments (PageId, UserId, CommentData) values (6, 9, 'Innovative regional toolset');
insert into comments (PageId, UserId, CommentData) values (3, 11, 'Operative bandwidth-monitored encoding');
insert into comments (PageId, UserId, CommentData) values (6, 7, 'Distributed bi-directional neural-net');
insert into comments (PageId, UserId, CommentData) values (3, 24, 'Function-based uniform Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (8, 17, 'Multi-channelled bottom-line contingency');
insert into comments (PageId, UserId, CommentData) values (2, 38, 'Implemented dynamic definition');
insert into comments (PageId, UserId, CommentData) values (5, 47, 'Diverse well-modulated infrastructure');
insert into comments (PageId, UserId, CommentData) values (3, 47, 'Mandatory directional frame');
insert into comments (PageId, UserId, CommentData) values (5, 47, 'Synergistic grid-enabled array');
insert into comments (PageId, UserId, CommentData) values (5, 19, 'Visionary systematic moratorium');
insert into comments (PageId, UserId, CommentData) values (4, 15, 'Inverse systemic time-frame');
insert into comments (PageId, UserId, CommentData) values (10, 20, 'Universal even-keeled structure');
insert into comments (PageId, UserId, CommentData) values (7, 40, 'Innovative attitude-oriented initiative');
insert into comments (PageId, UserId, CommentData) values (5, 1, 'Up-sized responsive application');
insert into comments (PageId, UserId, CommentData) values (6, 15, 'Profit-focused directional frame');
insert into comments (PageId, UserId, CommentData) values (8, 35, 'Diverse full-range throughput');
insert into comments (PageId, UserId, CommentData) values (7, 7, 'User-friendly full-range framework');
insert into comments (PageId, UserId, CommentData) values (3, 2, 'Compatible responsive moratorium');
insert into comments (PageId, UserId, CommentData) values (4, 6, 'Multi-lateral zero tolerance knowledge user');
insert into comments (PageId, UserId, CommentData) values (6, 35, 'Face to face regional help-desk');
insert into comments (PageId, UserId, CommentData) values (4, 7, 'Universal scalable instruction set');
insert into comments (PageId, UserId, CommentData) values (1, 22, 'Operative 3rd generation info-mediaries');
insert into comments (PageId, UserId, CommentData) values (5, 12, 'Vision-oriented systematic artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (10, 23, 'Up-sized optimal leverage');
insert into comments (PageId, UserId, CommentData) values (4, 26, 'Persevering holistic matrices');
insert into comments (PageId, UserId, CommentData) values (2, 37, 'Synergized impactful info-mediaries');
insert into comments (PageId, UserId, CommentData) values (1, 4, 'Diverse 6th generation Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (8, 22, 'Mandatory 3rd generation complexity');
insert into comments (PageId, UserId, CommentData) values (10, 22, 'Synergized incremental neural-net');
insert into comments (PageId, UserId, CommentData) values (9, 49, 'Decentralized fault-tolerant forecast');
insert into comments (PageId, UserId, CommentData) values (4, 36, 'Extended logistical monitoring');
insert into comments (PageId, UserId, CommentData) values (10, 30, 'Distributed fresh-thinking Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (8, 16, 'Decentralized zero administration Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (6, 45, 'Face to face local approach');
insert into comments (PageId, UserId, CommentData) values (3, 28, 'Cloned user-facing initiative');
insert into comments (PageId, UserId, CommentData) values (2, 25, 'Ameliorated local success');
insert into comments (PageId, UserId, CommentData) values (6, 18, 'Horizontal uniform conglomeration');
insert into comments (PageId, UserId, CommentData) values (3, 16, 'Profound exuding leverage');
insert into comments (PageId, UserId, CommentData) values (10, 2, 'Customizable impactful challenge');
insert into comments (PageId, UserId, CommentData) values (3, 3, 'Visionary even-keeled process improvement');
insert into comments (PageId, UserId, CommentData) values (5, 33, 'Inverse 3rd generation secured line');
insert into comments (PageId, UserId, CommentData) values (10, 28, 'Profit-focused systematic leverage');
insert into comments (PageId, UserId, CommentData) values (5, 15, 'Progressive bifurcated installation');
insert into comments (PageId, UserId, CommentData) values (10, 14, 'Reverse-engineered needs-based core');
insert into comments (PageId, UserId, CommentData) values (6, 41, 'Visionary interactive forecast');
insert into comments (PageId, UserId, CommentData) values (10, 28, 'Enhanced attitude-oriented encoding');
insert into comments (PageId, UserId, CommentData) values (3, 35, 'Reduced even-keeled secured line');
insert into comments (PageId, UserId, CommentData) values (3, 46, 'Diverse holistic circuit');
insert into comments (PageId, UserId, CommentData) values (8, 39, 'Fundamental background knowledge user');
insert into comments (PageId, UserId, CommentData) values (9, 39, 'Exclusive stable paradigm');
insert into comments (PageId, UserId, CommentData) values (4, 23, 'Reverse-engineered modular implementation');
insert into comments (PageId, UserId, CommentData) values (3, 12, 'Realigned multi-state methodology');
insert into comments (PageId, UserId, CommentData) values (9, 39, 'Front-line multi-state throughput');
insert into comments (PageId, UserId, CommentData) values (3, 49, 'User-friendly upward-trending database');
insert into comments (PageId, UserId, CommentData) values (9, 23, 'Devolved fresh-thinking array');
insert into comments (PageId, UserId, CommentData) values (7, 50, 'Decentralized encompassing matrices');
insert into comments (PageId, UserId, CommentData) values (10, 34, 'Seamless interactive matrices');
insert into comments (PageId, UserId, CommentData) values (8, 7, 'Re-engineered stable architecture');
insert into comments (PageId, UserId, CommentData) values (9, 42, 'Extended radical approach');
insert into comments (PageId, UserId, CommentData) values (8, 14, 'Quality-focused radical infrastructure');
insert into comments (PageId, UserId, CommentData) values (1, 11, 'Customer-focused executive encryption');
