insert into comments (PageId, UserId, CommentData) values (1, 48, 'Digitized maximized superstructure');
insert into comments (PageId, UserId, CommentData) values (5, 31, 'Horizontal bottom-line matrix');
insert into comments (PageId, UserId, CommentData) values (6, 37, 'Proactive scalable artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (2, 3, 'Streamlined multi-tasking infrastructure');
insert into comments (PageId, UserId, CommentData) values (1, 25, 'Managed global Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (9, 16, 'Quality-focused analyzing time-frame');
insert into comments (PageId, UserId, CommentData) values (10, 43, 'Digitized 24/7 product');
insert into comments (PageId, UserId, CommentData) values (8, 25, 'Business-focused empowering solution');
insert into comments (PageId, UserId, CommentData) values (10, 13, 'Programmable actuating focus group');
insert into comments (PageId, UserId, CommentData) values (3, 9, 'Customer-focused next generation hub');
insert into comments (PageId, UserId, CommentData) values (7, 27, 'User-centric object-oriented capacity');
insert into comments (PageId, UserId, CommentData) values (2, 11, 'Total bottom-line access');
insert into comments (PageId, UserId, CommentData) values (5, 44, 'Multi-layered foreground frame');
insert into comments (PageId, UserId, CommentData) values (1, 44, 'Multi-layered homogeneous benchmark');
insert into comments (PageId, UserId, CommentData) values (3, 33, 'Organized optimizing application');
insert into comments (PageId, UserId, CommentData) values (5, 26, 'Fully-configurable radical function');
insert into comments (PageId, UserId, CommentData) values (3, 38, 'Exclusive local implementation');
insert into comments (PageId, UserId, CommentData) values (3, 35, 'Open-architected 4th generation focus group');
insert into comments (PageId, UserId, CommentData) values (9, 49, 'Future-proofed bottom-line flexibility');
insert into comments (PageId, UserId, CommentData) values (6, 50, 'Implemented executive interface');
insert into comments (PageId, UserId, CommentData) values (3, 25, 'Vision-oriented exuding application');
insert into comments (PageId, UserId, CommentData) values (3, 5, 'Upgradable client-server neural-net');
insert into comments (PageId, UserId, CommentData) values (8, 8, 'Decentralized incremental capacity');
insert into comments (PageId, UserId, CommentData) values (4, 18, 'Reactive zero defect hub');
insert into comments (PageId, UserId, CommentData) values (10, 15, 'Diverse uniform alliance');
insert into comments (PageId, UserId, CommentData) values (2, 40, 'Decentralized multimedia matrix');
insert into comments (PageId, UserId, CommentData) values (1, 14, 'Quality-focused tertiary toolset');
insert into comments (PageId, UserId, CommentData) values (1, 23, 'Optional disintermediate matrix');
insert into comments (PageId, UserId, CommentData) values (4, 10, 'Realigned mission-critical neural-net');
insert into comments (PageId, UserId, CommentData) values (10, 9, 'Triple-buffered optimizing website');
insert into comments (PageId, UserId, CommentData) values (8, 3, 'Implemented zero tolerance local area network');
insert into comments (PageId, UserId, CommentData) values (4, 49, 'De-engineered neutral portal');
insert into comments (PageId, UserId, CommentData) values (8, 48, 'Optional executive system engine');
insert into comments (PageId, UserId, CommentData) values (5, 44, 'Grass-roots dynamic open system');
insert into comments (PageId, UserId, CommentData) values (2, 48, 'Cross-group 5th generation open system');
insert into comments (PageId, UserId, CommentData) values (10, 30, 'Reverse-engineered didactic standardization');
insert into comments (PageId, UserId, CommentData) values (1, 27, 'Proactive stable architecture');
insert into comments (PageId, UserId, CommentData) values (9, 48, 'Distributed user-facing product');
insert into comments (PageId, UserId, CommentData) values (7, 43, 'Decentralized mobile algorithm');
insert into comments (PageId, UserId, CommentData) values (2, 29, 'Optimized systemic help-desk');
insert into comments (PageId, UserId, CommentData) values (9, 36, 'Business-focused tangible toolset');
insert into comments (PageId, UserId, CommentData) values (2, 27, 'Fully-configurable even-keeled artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (9, 4, 'Decentralized eco-centric orchestration');
insert into comments (PageId, UserId, CommentData) values (6, 30, 'Open-source background installation');
insert into comments (PageId, UserId, CommentData) values (6, 37, 'Reduced upward-trending superstructure');
insert into comments (PageId, UserId, CommentData) values (5, 28, 'User-centric static capacity');
insert into comments (PageId, UserId, CommentData) values (3, 8, 'Public-key human-resource toolset');
insert into comments (PageId, UserId, CommentData) values (2, 35, 'Operative transitional benchmark');
insert into comments (PageId, UserId, CommentData) values (4, 20, 'Object-based analyzing database');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Innovative modular local area network');
insert into comments (PageId, UserId, CommentData) values (8, 2, 'User-centric scalable functionalities');
insert into comments (PageId, UserId, CommentData) values (2, 31, 'Ameliorated motivating Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (6, 16, 'Devolved well-modulated infrastructure');
insert into comments (PageId, UserId, CommentData) values (3, 7, 'Object-based coherent pricing structure');
insert into comments (PageId, UserId, CommentData) values (5, 21, 'Multi-tiered background capability');
insert into comments (PageId, UserId, CommentData) values (6, 47, 'Right-sized full-range alliance');
insert into comments (PageId, UserId, CommentData) values (7, 27, 'Cross-group mission-critical artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (7, 8, 'Cloned contextually-based collaboration');
insert into comments (PageId, UserId, CommentData) values (6, 22, 'Cross-platform global function');
insert into comments (PageId, UserId, CommentData) values (5, 26, 'Team-oriented impactful definition');
insert into comments (PageId, UserId, CommentData) values (6, 3, 'Fully-configurable demand-driven throughput');
insert into comments (PageId, UserId, CommentData) values (2, 4, 'Profit-focused impactful system engine');
insert into comments (PageId, UserId, CommentData) values (6, 27, 'Synchronised zero defect info-mediaries');
insert into comments (PageId, UserId, CommentData) values (2, 4, 'Implemented needs-based array');
insert into comments (PageId, UserId, CommentData) values (9, 41, 'Cloned human-resource architecture');
insert into comments (PageId, UserId, CommentData) values (4, 36, 'Organic exuding core');
insert into comments (PageId, UserId, CommentData) values (5, 15, 'Realigned optimal extranet');
insert into comments (PageId, UserId, CommentData) values (1, 41, 'Operative homogeneous data-warehouse');
insert into comments (PageId, UserId, CommentData) values (9, 31, 'Upgradable mobile neural-net');
insert into comments (PageId, UserId, CommentData) values (5, 47, 'Assimilated high-level extranet');
insert into comments (PageId, UserId, CommentData) values (2, 12, 'Function-based human-resource emulation');
insert into comments (PageId, UserId, CommentData) values (3, 31, 'Face to face object-oriented circuit');
insert into comments (PageId, UserId, CommentData) values (8, 16, 'Profound full-range flexibility');
insert into comments (PageId, UserId, CommentData) values (1, 4, 'Triple-buffered reciprocal database');
insert into comments (PageId, UserId, CommentData) values (6, 29, 'Total client-driven hierarchy');
insert into comments (PageId, UserId, CommentData) values (7, 3, 'Total tangible info-mediaries');
insert into comments (PageId, UserId, CommentData) values (8, 7, 'Object-based high-level project');
insert into comments (PageId, UserId, CommentData) values (9, 17, 'Multi-layered contextually-based benchmark');
insert into comments (PageId, UserId, CommentData) values (6, 27, 'Operative value-added functionalities');
insert into comments (PageId, UserId, CommentData) values (8, 44, 'Enterprise-wide dynamic task-force');
insert into comments (PageId, UserId, CommentData) values (8, 18, 'Switchable context-sensitive attitude');
insert into comments (PageId, UserId, CommentData) values (6, 42, 'Adaptive user-facing groupware');
insert into comments (PageId, UserId, CommentData) values (5, 28, 'Ergonomic bifurcated moratorium');
insert into comments (PageId, UserId, CommentData) values (1, 24, 'Stand-alone regional adapter');
insert into comments (PageId, UserId, CommentData) values (9, 33, 'Front-line responsive moratorium');
insert into comments (PageId, UserId, CommentData) values (4, 15, 'Re-engineered tangible Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (7, 9, 'Public-key heuristic forecast');
insert into comments (PageId, UserId, CommentData) values (7, 42, 'Triple-buffered impactful definition');
insert into comments (PageId, UserId, CommentData) values (6, 26, 'Multi-channelled maximized model');
insert into comments (PageId, UserId, CommentData) values (2, 24, 'Triple-buffered real-time hardware');
insert into comments (PageId, UserId, CommentData) values (1, 41, 'Cross-group multimedia internet solution');
insert into comments (PageId, UserId, CommentData) values (10, 50, 'Multi-tiered client-driven pricing structure');
insert into comments (PageId, UserId, CommentData) values (3, 11, 'Implemented directional analyzer');
insert into comments (PageId, UserId, CommentData) values (10, 42, 'Seamless stable groupware');
insert into comments (PageId, UserId, CommentData) values (1, 26, 'Cloned stable emulation');
insert into comments (PageId, UserId, CommentData) values (3, 43, 'Triple-buffered encompassing forecast');
insert into comments (PageId, UserId, CommentData) values (8, 31, 'Multi-lateral user-facing groupware');
insert into comments (PageId, UserId, CommentData) values (10, 16, 'Multi-lateral dedicated ability');
insert into comments (PageId, UserId, CommentData) values (8, 23, 'Multi-channelled motivating hub');
insert into comments (PageId, UserId, CommentData) values (7, 16, 'Ameliorated optimal toolset');
