insert into comments (PageId, UserId, CommentData) values (5, 6, 'Networked impactful moratorium');
insert into comments (PageId, UserId, CommentData) values (1, 20, 'Ergonomic modular customer loyalty');
insert into comments (PageId, UserId, CommentData) values (2, 46, 'Digitized secondary budgetary management');
insert into comments (PageId, UserId, CommentData) values (1, 3, 'Optional bandwidth-monitored emulation');
insert into comments (PageId, UserId, CommentData) values (2, 35, 'Synchronised 24/7 instruction set');
insert into comments (PageId, UserId, CommentData) values (3, 43, 'Assimilated non-volatile software');
insert into comments (PageId, UserId, CommentData) values (9, 10, 'Ergonomic reciprocal toolset');
insert into comments (PageId, UserId, CommentData) values (7, 49, 'Devolved discrete synergy');
insert into comments (PageId, UserId, CommentData) values (10, 24, 'Proactive eco-centric open system');
insert into comments (PageId, UserId, CommentData) values (1, 32, 'Monitored systemic installation');
insert into comments (PageId, UserId, CommentData) values (4, 5, 'Inverse bi-directional monitoring');
insert into comments (PageId, UserId, CommentData) values (4, 3, 'Cross-platform system-worthy database');
insert into comments (PageId, UserId, CommentData) values (1, 3, 'Organic homogeneous alliance');
insert into comments (PageId, UserId, CommentData) values (2, 20, 'Upgradable mobile model');
insert into comments (PageId, UserId, CommentData) values (7, 39, 'Advanced empowering synergy');
insert into comments (PageId, UserId, CommentData) values (4, 40, 'Organized clear-thinking strategy');
insert into comments (PageId, UserId, CommentData) values (4, 25, 'Polarised hybrid circuit');
insert into comments (PageId, UserId, CommentData) values (3, 38, 'Customizable bottom-line analyzer');
insert into comments (PageId, UserId, CommentData) values (10, 48, 'Phased client-server approach');
insert into comments (PageId, UserId, CommentData) values (4, 15, 'Secured full-range attitude');
insert into comments (PageId, UserId, CommentData) values (5, 25, 'Configurable composite contingency');
insert into comments (PageId, UserId, CommentData) values (7, 3, 'Horizontal reciprocal instruction set');
insert into comments (PageId, UserId, CommentData) values (8, 22, 'Networked tertiary interface');
insert into comments (PageId, UserId, CommentData) values (9, 30, 'Multi-tiered bi-directional installation');
insert into comments (PageId, UserId, CommentData) values (6, 27, 'Inverse solution-oriented Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (4, 24, 'Cloned stable process improvement');
insert into comments (PageId, UserId, CommentData) values (4, 16, 'Versatile local model');
insert into comments (PageId, UserId, CommentData) values (10, 34, 'Stand-alone attitude-oriented time-frame');
insert into comments (PageId, UserId, CommentData) values (2, 13, 'Compatible asymmetric instruction set');
insert into comments (PageId, UserId, CommentData) values (10, 25, 'De-engineered background firmware');
insert into comments (PageId, UserId, CommentData) values (6, 13, 'Networked value-added matrix');
insert into comments (PageId, UserId, CommentData) values (7, 36, 'Organic non-volatile capability');
insert into comments (PageId, UserId, CommentData) values (10, 12, 'Automated cohesive extranet');
insert into comments (PageId, UserId, CommentData) values (9, 27, 'Managed full-range structure');
insert into comments (PageId, UserId, CommentData) values (3, 6, 'Phased demand-driven functionalities');
insert into comments (PageId, UserId, CommentData) values (9, 24, 'Horizontal next generation customer loyalty');
insert into comments (PageId, UserId, CommentData) values (6, 1, 'Mandatory executive approach');
insert into comments (PageId, UserId, CommentData) values (3, 18, 'User-friendly full-range success');
insert into comments (PageId, UserId, CommentData) values (10, 48, 'Versatile interactive time-frame');
insert into comments (PageId, UserId, CommentData) values (5, 36, 'Adaptive 24/7 model');
insert into comments (PageId, UserId, CommentData) values (4, 35, 'Innovative static database');
insert into comments (PageId, UserId, CommentData) values (5, 1, 'Sharable systemic concept');
insert into comments (PageId, UserId, CommentData) values (3, 38, 'Cloned radical encoding');
insert into comments (PageId, UserId, CommentData) values (4, 44, 'Organic content-based standardization');
insert into comments (PageId, UserId, CommentData) values (10, 33, 'Managed non-volatile project');
insert into comments (PageId, UserId, CommentData) values (3, 43, 'Integrated full-range access');
insert into comments (PageId, UserId, CommentData) values (3, 41, 'Front-line dynamic budgetary management');
insert into comments (PageId, UserId, CommentData) values (7, 19, 'Monitored eco-centric artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (5, 6, 'Open-source radical encoding');
insert into comments (PageId, UserId, CommentData) values (1, 7, 'Digitized directional task-force');
insert into comments (PageId, UserId, CommentData) values (7, 5, 'User-friendly dedicated task-force');
insert into comments (PageId, UserId, CommentData) values (10, 23, 'Optional leading edge local area network');
insert into comments (PageId, UserId, CommentData) values (1, 34, 'Reverse-engineered contextually-based function');
insert into comments (PageId, UserId, CommentData) values (2, 37, 'Exclusive eco-centric complexity');
insert into comments (PageId, UserId, CommentData) values (4, 7, 'Proactive static structure');
insert into comments (PageId, UserId, CommentData) values (1, 22, 'Profound 6th generation implementation');
insert into comments (PageId, UserId, CommentData) values (2, 10, 'User-centric fresh-thinking solution');
insert into comments (PageId, UserId, CommentData) values (5, 49, 'Inverse client-driven firmware');
insert into comments (PageId, UserId, CommentData) values (4, 26, 'Horizontal executive initiative');
insert into comments (PageId, UserId, CommentData) values (1, 37, 'Optional tangible matrices');
insert into comments (PageId, UserId, CommentData) values (3, 4, 'Polarised logistical monitoring');
insert into comments (PageId, UserId, CommentData) values (7, 5, 'Open-architected foreground protocol');
insert into comments (PageId, UserId, CommentData) values (6, 42, 'Customizable 24 hour implementation');
insert into comments (PageId, UserId, CommentData) values (8, 30, 'Advanced asymmetric open system');
insert into comments (PageId, UserId, CommentData) values (3, 20, 'Persistent user-facing solution');
insert into comments (PageId, UserId, CommentData) values (10, 7, 'Re-engineered needs-based parallelism');
insert into comments (PageId, UserId, CommentData) values (1, 7, 'Expanded multimedia alliance');
insert into comments (PageId, UserId, CommentData) values (3, 33, 'Realigned responsive circuit');
insert into comments (PageId, UserId, CommentData) values (4, 22, 'Ergonomic composite portal');
insert into comments (PageId, UserId, CommentData) values (5, 37, 'Persevering 24 hour circuit');
insert into comments (PageId, UserId, CommentData) values (9, 49, 'Grass-roots user-facing attitude');
insert into comments (PageId, UserId, CommentData) values (3, 8, 'Triple-buffered grid-enabled paradigm');
insert into comments (PageId, UserId, CommentData) values (2, 37, 'Programmable contextually-based forecast');
insert into comments (PageId, UserId, CommentData) values (10, 37, 'Secured leading edge internet solution');
insert into comments (PageId, UserId, CommentData) values (9, 4, 'Intuitive methodical array');
insert into comments (PageId, UserId, CommentData) values (6, 4, 'Enhanced bifurcated functionalities');
insert into comments (PageId, UserId, CommentData) values (7, 20, 'Future-proofed global framework');
insert into comments (PageId, UserId, CommentData) values (10, 23, 'Versatile fault-tolerant archive');
insert into comments (PageId, UserId, CommentData) values (7, 42, 'Quality-focused client-driven Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (3, 31, 'Reverse-engineered systematic info-mediaries');
insert into comments (PageId, UserId, CommentData) values (1, 2, 'Re-contextualized attitude-oriented extranet');
insert into comments (PageId, UserId, CommentData) values (4, 24, 'Mandatory logistical array');
insert into comments (PageId, UserId, CommentData) values (6, 13, 'Cross-platform transitional success');
insert into comments (PageId, UserId, CommentData) values (4, 21, 'Upgradable contextually-based hierarchy');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Innovative real-time strategy');
insert into comments (PageId, UserId, CommentData) values (8, 9, 'Polarised empowering Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (8, 9, 'Visionary encompassing projection');
insert into comments (PageId, UserId, CommentData) values (1, 22, 'Centralized composite matrices');
insert into comments (PageId, UserId, CommentData) values (8, 12, 'Reverse-engineered discrete array');
insert into comments (PageId, UserId, CommentData) values (6, 11, 'Horizontal static definition');
insert into comments (PageId, UserId, CommentData) values (4, 20, 'Re-contextualized composite website');
insert into comments (PageId, UserId, CommentData) values (5, 26, 'Integrated explicit service-desk');
insert into comments (PageId, UserId, CommentData) values (6, 46, 'Grass-roots 5th generation complexity');
insert into comments (PageId, UserId, CommentData) values (7, 42, 'Optional reciprocal moratorium');
insert into comments (PageId, UserId, CommentData) values (1, 47, 'Compatible 4th generation throughput');
insert into comments (PageId, UserId, CommentData) values (10, 42, 'Stand-alone optimizing challenge');
insert into comments (PageId, UserId, CommentData) values (1, 27, 'Focused zero defect protocol');
insert into comments (PageId, UserId, CommentData) values (1, 4, 'Right-sized scalable throughput');
insert into comments (PageId, UserId, CommentData) values (5, 26, 'Polarised stable groupware');
insert into comments (PageId, UserId, CommentData) values (5, 36, 'Expanded client-server knowledge user');
