insert into comments (PageId, UserId, CommentData) values (10, 9, 'Compatible clear-thinking knowledge base');
insert into comments (PageId, UserId, CommentData) values (1, 17, 'Seamless incremental paradigm');
insert into comments (PageId, UserId, CommentData) values (4, 49, 'Open-architected logistical middleware');
insert into comments (PageId, UserId, CommentData) values (2, 49, 'Persevering leading edge concept');
insert into comments (PageId, UserId, CommentData) values (6, 25, 'Versatile clear-thinking extranet');
insert into comments (PageId, UserId, CommentData) values (7, 41, 'Automated modular leverage');
insert into comments (PageId, UserId, CommentData) values (3, 4, 'Down-sized contextually-based migration');
insert into comments (PageId, UserId, CommentData) values (10, 45, 'Object-based didactic matrix');
insert into comments (PageId, UserId, CommentData) values (7, 25, 'Managed hybrid groupware');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Networked clear-thinking extranet');
insert into comments (PageId, UserId, CommentData) values (5, 45, 'Business-focused 24/7 time-frame');
insert into comments (PageId, UserId, CommentData) values (7, 44, 'Business-focused demand-driven capability');
insert into comments (PageId, UserId, CommentData) values (10, 20, 'Cloned intermediate neural-net');
insert into comments (PageId, UserId, CommentData) values (10, 33, 'Diverse interactive product');
insert into comments (PageId, UserId, CommentData) values (4, 7, 'Multi-layered hybrid data-warehouse');
insert into comments (PageId, UserId, CommentData) values (2, 49, 'Synchronised directional adapter');
insert into comments (PageId, UserId, CommentData) values (8, 36, 'Organic incremental initiative');
insert into comments (PageId, UserId, CommentData) values (10, 30, 'Vision-oriented background portal');
insert into comments (PageId, UserId, CommentData) values (1, 28, 'Optional optimizing benchmark');
insert into comments (PageId, UserId, CommentData) values (8, 30, 'User-centric motivating knowledge base');
insert into comments (PageId, UserId, CommentData) values (6, 50, 'De-engineered composite alliance');
insert into comments (PageId, UserId, CommentData) values (1, 12, 'Integrated non-volatile database');
insert into comments (PageId, UserId, CommentData) values (8, 16, 'Open-architected real-time productivity');
insert into comments (PageId, UserId, CommentData) values (7, 32, 'Horizontal modular approach');
insert into comments (PageId, UserId, CommentData) values (2, 36, 'Ameliorated content-based Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (6, 10, 'Distributed fault-tolerant implementation');
insert into comments (PageId, UserId, CommentData) values (5, 24, 'Networked interactive core');
insert into comments (PageId, UserId, CommentData) values (3, 20, 'Cross-platform needs-based hub');
insert into comments (PageId, UserId, CommentData) values (2, 50, 'Business-focused maximized hub');
insert into comments (PageId, UserId, CommentData) values (7, 21, 'User-centric maximized conglomeration');
insert into comments (PageId, UserId, CommentData) values (9, 8, 'Down-sized secondary success');
insert into comments (PageId, UserId, CommentData) values (3, 25, 'Configurable neutral knowledge user');
insert into comments (PageId, UserId, CommentData) values (8, 30, 'Persevering 6th generation leverage');
insert into comments (PageId, UserId, CommentData) values (5, 38, 'Up-sized asymmetric secured line');
insert into comments (PageId, UserId, CommentData) values (8, 50, 'Re-engineered attitude-oriented groupware');
insert into comments (PageId, UserId, CommentData) values (1, 50, 'Phased logistical monitoring');
insert into comments (PageId, UserId, CommentData) values (9, 4, 'Function-based web-enabled orchestration');
insert into comments (PageId, UserId, CommentData) values (7, 26, 'Devolved 4th generation extranet');
insert into comments (PageId, UserId, CommentData) values (7, 23, 'Optional executive challenge');
insert into comments (PageId, UserId, CommentData) values (10, 9, 'Sharable global application');
insert into comments (PageId, UserId, CommentData) values (4, 20, 'Persistent system-worthy projection');
insert into comments (PageId, UserId, CommentData) values (3, 33, 'Profit-focused exuding concept');
insert into comments (PageId, UserId, CommentData) values (1, 5, 'Seamless high-level monitoring');
insert into comments (PageId, UserId, CommentData) values (5, 27, 'Operative discrete installation');
insert into comments (PageId, UserId, CommentData) values (3, 11, 'Mandatory well-modulated hierarchy');
insert into comments (PageId, UserId, CommentData) values (8, 44, 'Ergonomic radical system engine');
insert into comments (PageId, UserId, CommentData) values (5, 38, 'Face to face cohesive encoding');
insert into comments (PageId, UserId, CommentData) values (7, 23, 'Polarised intermediate matrices');
insert into comments (PageId, UserId, CommentData) values (6, 40, 'Inverse object-oriented hub');
insert into comments (PageId, UserId, CommentData) values (1, 49, 'User-friendly disintermediate intranet');
insert into comments (PageId, UserId, CommentData) values (4, 41, 'Profound multi-tasking initiative');
insert into comments (PageId, UserId, CommentData) values (9, 3, 'Pre-emptive 24 hour budgetary management');
insert into comments (PageId, UserId, CommentData) values (9, 21, 'Versatile background product');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Seamless fresh-thinking internet solution');
insert into comments (PageId, UserId, CommentData) values (8, 3, 'Realigned intangible artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (2, 24, 'Enhanced contextually-based matrix');
insert into comments (PageId, UserId, CommentData) values (8, 48, 'Ameliorated uniform middleware');
insert into comments (PageId, UserId, CommentData) values (3, 37, 'Multi-channelled upward-trending matrix');
insert into comments (PageId, UserId, CommentData) values (9, 3, 'De-engineered discrete function');
insert into comments (PageId, UserId, CommentData) values (6, 22, 'Exclusive optimal database');
insert into comments (PageId, UserId, CommentData) values (6, 11, 'Intuitive impactful approach');
insert into comments (PageId, UserId, CommentData) values (9, 43, 'Open-source mission-critical intranet');
insert into comments (PageId, UserId, CommentData) values (2, 10, 'Reverse-engineered directional productivity');
insert into comments (PageId, UserId, CommentData) values (3, 49, 'Devolved mobile capacity');
insert into comments (PageId, UserId, CommentData) values (7, 42, 'Right-sized bifurcated superstructure');
insert into comments (PageId, UserId, CommentData) values (4, 28, 'Stand-alone user-facing algorithm');
insert into comments (PageId, UserId, CommentData) values (3, 23, 'Polarised executive hierarchy');
insert into comments (PageId, UserId, CommentData) values (7, 29, 'Profit-focused demand-driven installation');
insert into comments (PageId, UserId, CommentData) values (1, 21, 'Customizable exuding policy');
insert into comments (PageId, UserId, CommentData) values (6, 35, 'Virtual 24 hour capability');
insert into comments (PageId, UserId, CommentData) values (3, 20, 'Cross-platform asymmetric interface');
insert into comments (PageId, UserId, CommentData) values (4, 24, 'Profit-focused interactive open system');
insert into comments (PageId, UserId, CommentData) values (2, 22, 'Secured multi-state internet solution');
insert into comments (PageId, UserId, CommentData) values (4, 47, 'Quality-focused 5th generation core');
insert into comments (PageId, UserId, CommentData) values (3, 27, 'Versatile executive standardization');
insert into comments (PageId, UserId, CommentData) values (6, 23, 'Reactive radical matrix');
insert into comments (PageId, UserId, CommentData) values (6, 42, 'De-engineered grid-enabled task-force');
insert into comments (PageId, UserId, CommentData) values (2, 38, 'Down-sized composite synergy');
insert into comments (PageId, UserId, CommentData) values (1, 33, 'Business-focused bottom-line definition');
insert into comments (PageId, UserId, CommentData) values (5, 41, 'Ergonomic systemic groupware');
insert into comments (PageId, UserId, CommentData) values (1, 28, 'Object-based even-keeled system engine');
insert into comments (PageId, UserId, CommentData) values (7, 6, 'Customer-focused demand-driven access');
insert into comments (PageId, UserId, CommentData) values (1, 4, 'Sharable real-time data-warehouse');
insert into comments (PageId, UserId, CommentData) values (8, 24, 'Open-source 3rd generation website');
insert into comments (PageId, UserId, CommentData) values (8, 6, 'Re-engineered grid-enabled emulation');
insert into comments (PageId, UserId, CommentData) values (2, 8, 'Profit-focused empowering structure');
insert into comments (PageId, UserId, CommentData) values (7, 3, 'Cross-platform full-range info-mediaries');
insert into comments (PageId, UserId, CommentData) values (1, 44, 'Multi-tiered hybrid support');
insert into comments (PageId, UserId, CommentData) values (5, 31, 'Virtual 4th generation Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (4, 44, 'Mandatory bottom-line focus group');
insert into comments (PageId, UserId, CommentData) values (2, 4, 'Persevering cohesive artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (3, 4, 'Multi-lateral client-driven policy');
insert into comments (PageId, UserId, CommentData) values (5, 8, 'Intuitive encompassing core');
insert into comments (PageId, UserId, CommentData) values (2, 38, 'Innovative optimizing instruction set');
insert into comments (PageId, UserId, CommentData) values (8, 22, 'Realigned intermediate paradigm');
insert into comments (PageId, UserId, CommentData) values (5, 36, 'Compatible coherent ability');
insert into comments (PageId, UserId, CommentData) values (8, 38, 'Profit-focused encompassing archive');
insert into comments (PageId, UserId, CommentData) values (8, 10, 'Implemented zero defect capacity');
insert into comments (PageId, UserId, CommentData) values (6, 30, 'Assimilated exuding task-force');
insert into comments (PageId, UserId, CommentData) values (5, 37, 'Mandatory motivating hardware');
