insert into comments (PageId, UserId, CommentData) values (10, 27, 'Customer-focused web-enabled knowledge base');
insert into comments (PageId, UserId, CommentData) values (6, 32, 'Multi-channelled mission-critical adapter');
insert into comments (PageId, UserId, CommentData) values (3, 41, 'Intuitive methodical workforce');
insert into comments (PageId, UserId, CommentData) values (7, 37, 'Right-sized solution-oriented model');
insert into comments (PageId, UserId, CommentData) values (9, 29, 'Assimilated tangible Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (4, 33, 'Self-enabling transitional infrastructure');
insert into comments (PageId, UserId, CommentData) values (2, 38, 'Open-architected empowering encoding');
insert into comments (PageId, UserId, CommentData) values (3, 9, 'Enhanced 3rd generation structure');
insert into comments (PageId, UserId, CommentData) values (8, 13, 'Down-sized clear-thinking infrastructure');
insert into comments (PageId, UserId, CommentData) values (8, 30, 'Phased solution-oriented functionalities');
insert into comments (PageId, UserId, CommentData) values (1, 29, 'Multi-layered optimizing emulation');
insert into comments (PageId, UserId, CommentData) values (4, 1, 'Customer-focused real-time approach');
insert into comments (PageId, UserId, CommentData) values (7, 30, 'Exclusive object-oriented utilisation');
insert into comments (PageId, UserId, CommentData) values (2, 4, 'Persevering optimizing orchestration');
insert into comments (PageId, UserId, CommentData) values (1, 27, 'Inverse stable encryption');
insert into comments (PageId, UserId, CommentData) values (5, 24, 'Configurable heuristic project');
insert into comments (PageId, UserId, CommentData) values (6, 13, 'Face to face context-sensitive flexibility');
insert into comments (PageId, UserId, CommentData) values (6, 32, 'Versatile regional superstructure');
insert into comments (PageId, UserId, CommentData) values (9, 2, 'Centralized multi-state info-mediaries');
insert into comments (PageId, UserId, CommentData) values (3, 38, 'Synchronised multi-state extranet');
insert into comments (PageId, UserId, CommentData) values (9, 24, 'Focused even-keeled time-frame');
insert into comments (PageId, UserId, CommentData) values (3, 36, 'Team-oriented explicit extranet');
insert into comments (PageId, UserId, CommentData) values (7, 23, 'Vision-oriented bottom-line system engine');
insert into comments (PageId, UserId, CommentData) values (1, 36, 'Proactive explicit knowledge user');
insert into comments (PageId, UserId, CommentData) values (9, 5, 'Monitored upward-trending complexity');
insert into comments (PageId, UserId, CommentData) values (10, 8, 'Re-contextualized grid-enabled success');
insert into comments (PageId, UserId, CommentData) values (7, 12, 'Face to face logistical protocol');
insert into comments (PageId, UserId, CommentData) values (1, 13, 'Programmable encompassing neural-net');
insert into comments (PageId, UserId, CommentData) values (5, 11, 'Self-enabling full-range hub');
insert into comments (PageId, UserId, CommentData) values (7, 40, 'Synergized analyzing database');
insert into comments (PageId, UserId, CommentData) values (10, 21, 'Exclusive incremental array');
insert into comments (PageId, UserId, CommentData) values (5, 35, 'Down-sized national parallelism');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Adaptive didactic monitoring');
insert into comments (PageId, UserId, CommentData) values (10, 26, 'Assimilated actuating artificial intelligence');
insert into comments (PageId, UserId, CommentData) values (8, 49, 'Multi-layered object-oriented success');
insert into comments (PageId, UserId, CommentData) values (7, 32, 'Cross-group logistical productivity');
insert into comments (PageId, UserId, CommentData) values (10, 41, 'Synchronised intangible budgetary management');
insert into comments (PageId, UserId, CommentData) values (7, 44, 'Switchable systematic challenge');
insert into comments (PageId, UserId, CommentData) values (4, 34, 'Decentralized tertiary internet solution');
insert into comments (PageId, UserId, CommentData) values (3, 15, 'Face to face bottom-line knowledge base');
insert into comments (PageId, UserId, CommentData) values (7, 30, 'Adaptive zero defect encryption');
insert into comments (PageId, UserId, CommentData) values (1, 50, 'Multi-layered regional customer loyalty');
insert into comments (PageId, UserId, CommentData) values (3, 11, 'Team-oriented object-oriented protocol');
insert into comments (PageId, UserId, CommentData) values (4, 3, 'User-friendly zero defect analyzer');
insert into comments (PageId, UserId, CommentData) values (2, 13, 'Open-source regional emulation');
insert into comments (PageId, UserId, CommentData) values (8, 19, 'Balanced solution-oriented throughput');
insert into comments (PageId, UserId, CommentData) values (1, 19, 'Sharable 5th generation synergy');
insert into comments (PageId, UserId, CommentData) values (10, 42, 'Total systemic framework');
insert into comments (PageId, UserId, CommentData) values (8, 39, 'Persistent 24 hour focus group');
insert into comments (PageId, UserId, CommentData) values (7, 42, 'Switchable optimizing task-force');
insert into comments (PageId, UserId, CommentData) values (6, 2, 'Optional asymmetric contingency');
insert into comments (PageId, UserId, CommentData) values (8, 49, 'Cross-platform systemic attitude');
insert into comments (PageId, UserId, CommentData) values (5, 1, 'Open-architected homogeneous product');
insert into comments (PageId, UserId, CommentData) values (3, 41, 'Decentralized secondary middleware');
insert into comments (PageId, UserId, CommentData) values (1, 25, 'Assimilated explicit paradigm');
insert into comments (PageId, UserId, CommentData) values (8, 39, 'Synergistic demand-driven website');
insert into comments (PageId, UserId, CommentData) values (1, 13, 'Profit-focused systematic emulation');
insert into comments (PageId, UserId, CommentData) values (9, 18, 'Implemented real-time conglomeration');
insert into comments (PageId, UserId, CommentData) values (1, 5, 'Devolved impactful open architecture');
insert into comments (PageId, UserId, CommentData) values (6, 30, 'Re-engineered 3rd generation software');
insert into comments (PageId, UserId, CommentData) values (8, 19, 'Assimilated homogeneous monitoring');
insert into comments (PageId, UserId, CommentData) values (8, 27, 'Reactive heuristic knowledge user');
insert into comments (PageId, UserId, CommentData) values (10, 39, 'Ameliorated directional matrices');
insert into comments (PageId, UserId, CommentData) values (4, 49, 'Adaptive web-enabled extranet');
insert into comments (PageId, UserId, CommentData) values (9, 45, 'Digitized hybrid collaboration');
insert into comments (PageId, UserId, CommentData) values (10, 22, 'Object-based local process improvement');
insert into comments (PageId, UserId, CommentData) values (10, 34, 'Profit-focused mobile flexibility');
insert into comments (PageId, UserId, CommentData) values (3, 45, 'Multi-lateral attitude-oriented complexity');
insert into comments (PageId, UserId, CommentData) values (3, 34, 'Customizable demand-driven software');
insert into comments (PageId, UserId, CommentData) values (9, 45, 'Future-proofed non-volatile local area network');
insert into comments (PageId, UserId, CommentData) values (3, 47, 'Cloned encompassing strategy');
insert into comments (PageId, UserId, CommentData) values (7, 36, 'Fully-configurable encompassing standardization');
insert into comments (PageId, UserId, CommentData) values (10, 7, 'Reduced zero administration methodology');
insert into comments (PageId, UserId, CommentData) values (3, 12, 'Balanced context-sensitive solution');
insert into comments (PageId, UserId, CommentData) values (4, 2, 'Configurable bandwidth-monitored data-warehouse');
insert into comments (PageId, UserId, CommentData) values (6, 17, 'Enterprise-wide radical adapter');
insert into comments (PageId, UserId, CommentData) values (3, 2, 'Proactive zero tolerance collaboration');
insert into comments (PageId, UserId, CommentData) values (1, 38, 'Sharable directional throughput');
insert into comments (PageId, UserId, CommentData) values (4, 1, 'Customer-focused asynchronous collaboration');
insert into comments (PageId, UserId, CommentData) values (2, 23, 'Distributed multi-state circuit');
insert into comments (PageId, UserId, CommentData) values (4, 33, 'Profit-focused next generation system engine');
insert into comments (PageId, UserId, CommentData) values (2, 44, 'Fully-configurable coherent emulation');
insert into comments (PageId, UserId, CommentData) values (4, 4, 'Right-sized high-level circuit');
insert into comments (PageId, UserId, CommentData) values (6, 26, 'Expanded grid-enabled migration');
insert into comments (PageId, UserId, CommentData) values (3, 41, 'Re-contextualized well-modulated system engine');
insert into comments (PageId, UserId, CommentData) values (3, 8, 'Cloned interactive circuit');
insert into comments (PageId, UserId, CommentData) values (3, 18, 'Streamlined client-driven alliance');
insert into comments (PageId, UserId, CommentData) values (9, 10, 'Open-source reciprocal product');
insert into comments (PageId, UserId, CommentData) values (7, 2, 'Upgradable contextually-based orchestration');
insert into comments (PageId, UserId, CommentData) values (6, 14, 'Up-sized optimal hub');
insert into comments (PageId, UserId, CommentData) values (1, 33, 'Compatible local website');
insert into comments (PageId, UserId, CommentData) values (1, 35, 'Enterprise-wide 4th generation customer loyalty');
insert into comments (PageId, UserId, CommentData) values (8, 11, 'Realigned cohesive instruction set');
insert into comments (PageId, UserId, CommentData) values (3, 6, 'Mandatory zero administration middleware');
insert into comments (PageId, UserId, CommentData) values (8, 18, 'Realigned leading edge algorithm');
insert into comments (PageId, UserId, CommentData) values (6, 22, 'Function-based value-added installation');
insert into comments (PageId, UserId, CommentData) values (9, 33, 'Extended maximized application');
insert into comments (PageId, UserId, CommentData) values (9, 11, 'Fundamental even-keeled conglomeration');
insert into comments (PageId, UserId, CommentData) values (10, 40, 'Extended coherent time-frame');
insert into comments (PageId, UserId, CommentData) values (3, 32, 'Universal didactic array');
insert into comments (PageId, UserId, CommentData) values (5, 31, 'Up-sized dedicated encryption');
insert into comments (PageId, UserId, CommentData) values (10, 9, 'Extended regional array');
insert into comments (PageId, UserId, CommentData) values (4, 26, 'Virtual exuding local area network');
insert into comments (PageId, UserId, CommentData) values (3, 30, 'Advanced directional internet solution');
insert into comments (PageId, UserId, CommentData) values (10, 38, 'Profit-focused radical workforce');
insert into comments (PageId, UserId, CommentData) values (6, 24, 'Cross-group encompassing array');
insert into comments (PageId, UserId, CommentData) values (7, 29, 'Diverse mission-critical open architecture');
insert into comments (PageId, UserId, CommentData) values (7, 46, 'Intuitive fresh-thinking application');
insert into comments (PageId, UserId, CommentData) values (2, 45, 'Automated 24/7 data-warehouse');
insert into comments (PageId, UserId, CommentData) values (3, 43, 'Ergonomic zero defect infrastructure');
insert into comments (PageId, UserId, CommentData) values (7, 19, 'Object-based directional initiative');
insert into comments (PageId, UserId, CommentData) values (8, 21, 'Inverse systematic implementation');
insert into comments (PageId, UserId, CommentData) values (5, 32, 'Programmable bifurcated task-force');
insert into comments (PageId, UserId, CommentData) values (5, 38, 'Triple-buffered multi-tasking local area network');
insert into comments (PageId, UserId, CommentData) values (4, 15, 'Enhanced homogeneous time-frame');
insert into comments (PageId, UserId, CommentData) values (4, 37, 'Multi-channelled contextually-based projection');
insert into comments (PageId, UserId, CommentData) values (2, 33, 'Object-based mobile attitude');
insert into comments (PageId, UserId, CommentData) values (4, 22, 'Multi-layered user-facing groupware');
insert into comments (PageId, UserId, CommentData) values (8, 7, 'User-friendly mobile encryption');
insert into comments (PageId, UserId, CommentData) values (6, 29, 'Total secondary flexibility');
insert into comments (PageId, UserId, CommentData) values (5, 42, 'Managed clear-thinking adapter');
insert into comments (PageId, UserId, CommentData) values (2, 18, 'Programmable responsive matrix');
insert into comments (PageId, UserId, CommentData) values (7, 6, 'Intuitive stable framework');
insert into comments (PageId, UserId, CommentData) values (5, 23, 'Organic didactic utilisation');
insert into comments (PageId, UserId, CommentData) values (5, 12, 'Seamless eco-centric flexibility');
insert into comments (PageId, UserId, CommentData) values (7, 40, 'Cloned multimedia portal');
insert into comments (PageId, UserId, CommentData) values (2, 9, 'Innovative holistic circuit');
insert into comments (PageId, UserId, CommentData) values (3, 49, 'Polarised background encoding');
insert into comments (PageId, UserId, CommentData) values (8, 30, 'Visionary composite hierarchy');
insert into comments (PageId, UserId, CommentData) values (7, 15, 'Persevering responsive algorithm');
insert into comments (PageId, UserId, CommentData) values (9, 49, 'Diverse object-oriented infrastructure');
insert into comments (PageId, UserId, CommentData) values (3, 42, 'User-friendly upward-trending task-force');
insert into comments (PageId, UserId, CommentData) values (6, 38, 'Stand-alone maximized synergy');
insert into comments (PageId, UserId, CommentData) values (4, 10, 'Expanded leading edge function');
insert into comments (PageId, UserId, CommentData) values (3, 44, 'Open-source fault-tolerant protocol');
insert into comments (PageId, UserId, CommentData) values (3, 9, 'Fundamental bandwidth-monitored core');
insert into comments (PageId, UserId, CommentData) values (4, 46, 'Cross-platform systematic standardization');
insert into comments (PageId, UserId, CommentData) values (3, 20, 'Future-proofed user-facing concept');
insert into comments (PageId, UserId, CommentData) values (7, 44, 'Networked dynamic synergy');
insert into comments (PageId, UserId, CommentData) values (3, 30, 'Polarised disintermediate groupware');
insert into comments (PageId, UserId, CommentData) values (2, 17, 'Up-sized demand-driven emulation');
insert into comments (PageId, UserId, CommentData) values (9, 12, 'Multi-layered cohesive database');
insert into comments (PageId, UserId, CommentData) values (2, 11, 'Sharable incremental Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (2, 26, 'Inverse 3rd generation functionalities');
insert into comments (PageId, UserId, CommentData) values (6, 1, 'Persistent systematic policy');
insert into comments (PageId, UserId, CommentData) values (10, 12, 'Enterprise-wide zero administration data-warehouse');
insert into comments (PageId, UserId, CommentData) values (8, 21, 'Balanced well-modulated pricing structure');
insert into comments (PageId, UserId, CommentData) values (9, 31, 'Reverse-engineered 5th generation service-desk');
insert into comments (PageId, UserId, CommentData) values (6, 35, 'Fully-configurable zero tolerance website');
insert into comments (PageId, UserId, CommentData) values (5, 39, 'User-friendly grid-enabled approach');
insert into comments (PageId, UserId, CommentData) values (1, 30, 'Phased 24 hour analyzer');
insert into comments (PageId, UserId, CommentData) values (9, 5, 'Intuitive actuating Graphic Interface');
insert into comments (PageId, UserId, CommentData) values (4, 3, 'Optimized composite superstructure');
insert into comments (PageId, UserId, CommentData) values (3, 41, 'Persevering contextually-based flexibility');
insert into comments (PageId, UserId, CommentData) values (3, 27, 'Decentralized impactful process improvement');
insert into comments (PageId, UserId, CommentData) values (2, 11, 'Diverse asynchronous help-desk');
insert into comments (PageId, UserId, CommentData) values (7, 32, 'Grass-roots bifurcated local area network');
insert into comments (PageId, UserId, CommentData) values (3, 2, 'Compatible logistical structure');
insert into comments (PageId, UserId, CommentData) values (9, 13, 'Organized 3rd generation productivity');
insert into comments (PageId, UserId, CommentData) values (5, 26, 'Cross-group coherent standardization');
insert into comments (PageId, UserId, CommentData) values (9, 1, 'Streamlined multi-tasking projection');
insert into comments (PageId, UserId, CommentData) values (3, 16, 'Visionary bifurcated local area network');
insert into comments (PageId, UserId, CommentData) values (9, 12, 'Organic explicit Graphical User Interface');
insert into comments (PageId, UserId, CommentData) values (8, 11, 'Face to face 24 hour synergy');
insert into comments (PageId, UserId, CommentData) values (6, 23, 'Secured grid-enabled ability');
insert into comments (PageId, UserId, CommentData) values (6, 47, 'Robust tertiary middleware');
insert into comments (PageId, UserId, CommentData) values (10, 34, 'Multi-layered zero administration throughput');
insert into comments (PageId, UserId, CommentData) values (4, 11, 'Persevering heuristic structure');
insert into comments (PageId, UserId, CommentData) values (4, 8, 'Profit-focused cohesive matrix');
insert into comments (PageId, UserId, CommentData) values (8, 38, 'Devolved background approach');
insert into comments (PageId, UserId, CommentData) values (4, 43, 'Ameliorated cohesive conglomeration');
insert into comments (PageId, UserId, CommentData) values (5, 18, 'Automated coherent installation');
insert into comments (PageId, UserId, CommentData) values (3, 19, 'Public-key web-enabled approach');
insert into comments (PageId, UserId, CommentData) values (3, 25, 'Cross-group explicit local area network');
insert into comments (PageId, UserId, CommentData) values (6, 25, 'Progressive demand-driven forecast');
insert into comments (PageId, UserId, CommentData) values (6, 32, 'Horizontal holistic capability');
insert into comments (PageId, UserId, CommentData) values (6, 21, 'Persistent 24 hour focus group');
insert into comments (PageId, UserId, CommentData) values (1, 7, 'Enhanced needs-based interface');
insert into comments (PageId, UserId, CommentData) values (6, 15, 'Balanced systematic function');
insert into comments (PageId, UserId, CommentData) values (2, 42, 'Secured grid-enabled system engine');
insert into comments (PageId, UserId, CommentData) values (5, 15, 'Organic analyzing benchmark');
insert into comments (PageId, UserId, CommentData) values (9, 24, 'Networked fault-tolerant software');
insert into comments (PageId, UserId, CommentData) values (9, 40, 'Customer-focused dedicated website');
insert into comments (PageId, UserId, CommentData) values (1, 50, 'Stand-alone scalable challenge');
insert into comments (PageId, UserId, CommentData) values (1, 40, 'Re-engineered directional instruction set');
insert into comments (PageId, UserId, CommentData) values (7, 14, 'Fundamental fault-tolerant contingency');
insert into comments (PageId, UserId, CommentData) values (10, 21, 'Persevering dynamic monitoring');
insert into comments (PageId, UserId, CommentData) values (9, 34, 'Realigned system-worthy frame');
insert into comments (PageId, UserId, CommentData) values (4, 32, 'Seamless responsive ability');
insert into comments (PageId, UserId, CommentData) values (10, 9, 'Exclusive logistical secured line');
insert into comments (PageId, UserId, CommentData) values (6, 41, 'Organized cohesive groupware');
insert into comments (PageId, UserId, CommentData) values (2, 16, 'Operative zero defect middleware');
insert into comments (PageId, UserId, CommentData) values (6, 15, 'Multi-layered background service-desk');
insert into comments (PageId, UserId, CommentData) values (1, 28, 'Adaptive holistic archive');
insert into comments (PageId, UserId, CommentData) values (5, 21, 'Intuitive system-worthy attitude');
insert into comments (PageId, UserId, CommentData) values (3, 11, 'Organic 4th generation complexity');
insert into comments (PageId, UserId, CommentData) values (2, 47, 'Inverse disintermediate success');
insert into comments (PageId, UserId, CommentData) values (2, 27, 'Configurable composite monitoring');
insert into comments (PageId, UserId, CommentData) values (7, 41, 'Operative 24 hour service-desk');
insert into comments (PageId, UserId, CommentData) values (8, 4, 'Synergistic even-keeled groupware');
