// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dblayer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	Commentid   int32
	Pageid      int32
	Userid      int32
	Createdat   pgtype.Timestamp
	Editedbool  pgtype.Bool
	Upvotes     pgtype.Int4
	Downvotes   pgtype.Int4
	Commentdata string
	Parentid    pgtype.Int4
}

type Page struct {
	Pageurl       string
	Pageid        pgtype.Int4
	Commentscount pgtype.Int4
	Createdat     pgtype.Timestamp
}

type User struct {
	Userid    int32
	Username  string
	Firstname string
	Lastname  string
	Emailid   string
}

type Userrelation struct {
	Vieweruserid    int32
	Commentoruserid int32
	Tag             string
	Positivity      bool
}
