// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: userrealtions.sql

package dblayer

import (
	"context"
)

const createUserRelation = `-- name: CreateUserRelation :exec
INSERT INTO UserRelations (
    ViewerUserId, CommentorUserId, Tag, Positivity
) VALUES (
    $1, $2, $3, $4
)
`

type CreateUserRelationParams struct {
	Vieweruserid    int32
	Commentoruserid int32
	Tag             string
	Positivity      bool
}

func (q *Queries) CreateUserRelation(ctx context.Context, arg CreateUserRelationParams) error {
	_, err := q.db.Exec(ctx, createUserRelation,
		arg.Vieweruserid,
		arg.Commentoruserid,
		arg.Tag,
		arg.Positivity,
	)
	return err
}

const deleteUserRelation = `-- name: DeleteUserRelation :exec
DELETE FROM UserRelations
WHERE ViewerUserId = $1 AND CommentorUserId = $2
`

type DeleteUserRelationParams struct {
	Vieweruserid    int32
	Commentoruserid int32
}

func (q *Queries) DeleteUserRelation(ctx context.Context, arg DeleteUserRelationParams) error {
	_, err := q.db.Exec(ctx, deleteUserRelation, arg.Vieweruserid, arg.Commentoruserid)
	return err
}
